version: "3.1"

services:
  web:
    build: aci-helloworld
    image: danielscholl/aci-helloworld
    ports:
      - "8080:80"

  sidecar:
    build: aci-sidecar
    image: danielscholl/aci-sidecar
    environment:
      WEB_PORT: 80
      WEB_HOST: web
    links:
      - web


